### ISSUE TITLE
Build (and publish) native binary

### ISSUE THREAD

**Issue by vorburger** [enola-dev/enola#337]
Using https://github.com/sgammon/rules_graalvm (not https://github.com/andyscott/rules_graal), build a native `enola` binary.

Distribute it, like #334.

**Comment by vorburger** [comment]
* https://github.com/sgammon/rules_graalvm/issues/401
* https://github.com/sgammon/rules_graalvm/issues/556
* https://github.com/sgammon/rules_graalvm/issues/555

**Comment by vorburger** [comment]
#1622 for #1231 is currently stuck and fails due to:

```
/nix/store/8qmr9i8i5lgac3jyba331izf8j09ddsa-binutils-2.43.1/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:202)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.runLinkerCommand(NativeImageViaCC.java:152)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:118)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:741)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
```

As the native image doesn't work at all anyway, and it would likely be quite a bit of work to fully fix (finish) it, it's time to remove it again, for now; see #1637.

When (if) I ever pick this up, I suspect that it will be easier to just not bother using https://github.com/sgammon/rules_graalvm at all anymore, and instead simply install Graal via Nix, and then launch the equivalent GraalVM native image build command from a script.
