### ISSUE TITLE
Devcontainer doesn't work on Fedora

### ISSUE THREAD

**Issue by vorburger** [enola-dev/enola#435]
When opening this project (as of b14570767cbd791e8bdb01999239d10e90e250ef) with VSC,

it will ask something along the lines of "using the dev container [introduced around d7cec7ef17e0e43bdb5520f65fec11777e32542e] of this repository" (locally in VSC, not in a Codespace).

At least on Fedora 39, with `podman version 4.8.3` (with `podman-docker`), this doesn't quite seem to work, and fails like this:

```
[2024-01-27T22:07:21.014Z] Dev Containers 0.327.0 in VS Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681).
[2024-01-27T22:07:21.014Z] Start: Resolving Remote
[2024-01-27T22:07:21.068Z] Setting up container for folder or workspace: /home/vorburger/git/github.com/enola-dev/enola
[2024-01-27T22:07:21.069Z] Host: unix:///run/user/1000/podman/podman.sock
[2024-01-27T22:07:21.092Z] Start: Check Docker is running
[2024-01-27T22:07:21.094Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2024-01-27T22:07:21.285Z] Stop (191 ms): Run: docker version --format {{.Server.APIVersion}}
[2024-01-27T22:07:21.286Z] Server API version: 4.8.3
[2024-01-27T22:07:21.295Z] Stop (203 ms): Check Docker is running
[2024-01-27T22:07:21.299Z] Start: Run: docker volume ls -q
[2024-01-27T22:07:21.522Z] Stop (223 ms): Run: docker volume ls -q
[2024-01-27T22:07:21.523Z] Start: Run: docker volume create vscode
[2024-01-27T22:07:21.743Z] Stop (220 ms): Run: docker volume create vscode
[2024-01-27T22:07:21.745Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/vorburger/git/github.com/enola-dev/enola --filter label=vsch.quality=stable
[2024-01-27T22:07:21.943Z] Stop (198 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/home/vorburger/git/github.com/enola-dev/enola --filter label=vsch.quality=stable
[2024-01-27T22:07:21.948Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --filter label=devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json
[2024-01-27T22:07:22.149Z] Stop (201 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --filter label=devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json
[2024-01-27T22:07:22.153Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola
[2024-01-27T22:07:22.395Z] Stop (242 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola
[2024-01-27T22:07:22.400Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola
[2024-01-27T22:07:22.559Z] Stop (159 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola
[2024-01-27T22:07:22.565Z] Start: Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/vorburger/git/github.com/enola-dev/enola --id-label devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --id-label devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json --mount-workspace-git-root
[2024-01-27T22:07:23.498Z] @devcontainers/cli 0.54.1. Node.js v18.15.0. linux 6.6.12-200.fc39.x86_64 x64.
[2024-01-27T22:07:23.497Z] Start: Run: git rev-parse --show-cdup
[2024-01-27T22:07:23.566Z] Stop (69 ms): Run: git rev-parse --show-cdup
[2024-01-27T22:07:23.577Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --filter label=devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json
[2024-01-27T22:07:23.742Z] Stop (165 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --filter label=devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json
[2024-01-27T22:07:23.784Z] Stop (1219 ms): Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/vorburger/git/github.com/enola-dev/enola --id-label devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --id-label devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json --mount-workspace-git-root
[2024-01-27T22:07:23.787Z] Start: Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/vorburger/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-8061b729-cfe5-4fee-9e2a-d7af1ab72fea1706393238847 --workspace-folder /home/vorburger/git/github.com/enola-dev/enola --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --id-label devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-01-27T22:07:25.504Z] @devcontainers/cli 0.54.1. Node.js v18.15.0. linux 6.6.12-200.fc39.x86_64 x64.
[2024-01-27T22:07:25.504Z] Start: Run: docker buildx version
[2024-01-27T22:07:25.871Z] Stop (367 ms): Run: docker buildx version
[2024-01-27T22:07:25.872Z] buildah 1.33.2
[2024-01-27T22:07:25.873Z] Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.

[2024-01-27T22:07:25.873Z] Start: Resolving Remote
[2024-01-27T22:07:25.894Z] Start: Run: git rev-parse --show-cdup
[2024-01-27T22:07:25.915Z] Stop (21 ms): Run: git rev-parse --show-cdup
[2024-01-27T22:07:25.931Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --filter label=devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json
[2024-01-27T22:07:26.105Z] Stop (174 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --filter label=devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json
[2024-01-27T22:07:26.107Z] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/universal:2-linux
[2024-01-27T22:07:26.422Z] Stop (315 ms): Run: docker inspect --type image mcr.microsoft.com/devcontainers/universal:2-linux
[2024-01-27T22:07:26.446Z] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/java:1'...
[2024-01-27T22:07:26.446Z] * Processing feature: ghcr.io/devcontainers/features/java:1
[2024-01-27T22:07:26.683Z] Start: Run: docker-credential-pass get
[2024-01-27T22:07:26.730Z] Stop (47 ms): Run: docker-credential-pass get
[2024-01-27T22:07:26.755Z] Stop (72 ms): Run: docker-credential-pass get
[2024-01-27T22:07:27.106Z] * Processing feature: ghcr.io/devcontainers/features/common-utils
[2024-01-27T22:07:27.290Z] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[2024-01-27T22:07:27.305Z] * Fetching feature: java_0_oci
[2024-01-27T22:07:27.716Z] * Fetched feature: java_0_oci version 1.3.0
[2024-01-27T22:07:27.739Z] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-vorburger/container-features/0.54.1-1706393246427 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/universal:2-linux --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-enola-577cbb2e9b094215f15980dd5f49c2e1bb2879f51a769be6f23be75ff412ddd4-features -f /tmp/devcontainercli-vorburger/container-features/0.54.1-1706393246427/Dockerfile.extended /home/vorburger/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2024-01-27T22:07:27.770Z] Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[2024-01-27T22:07:27.883Z] [1/2] STEP 1/4: FROM mcr.microsoft.com/devcontainers/universal:2-linux AS dev_containers_feature_content_normalize
[2024-01-27T22:07:28.120Z] [1/2] STEP 2/4: USER root
[2024-01-27T22:07:28.145Z] --> Using cache 3939e9e2b13c3a870e3d13d838a0dd9bd2437433c8f5430c936e73c186889c36
--> 3939e9e2b13c
[2024-01-27T22:07:28.201Z] [1/2] STEP 3/4: COPY --from=dev_containers_feature_content_source devcontainer-features.builtin.env /tmp/build-features/
[2024-01-27T22:07:28.970Z] --> Using cache f960425961b1b22bd0b21b5319b632c2ddc6d404e37b649796ad3c6e171be187
[2024-01-27T22:07:28.970Z]
[2024-01-27T22:07:28.970Z] --> f960425961b1
[2024-01-27T22:07:28.970Z]
[2024-01-27T22:07:29.007Z] [1/2] STEP 4/4: RUN chmod -R 0755 /tmp/build-features/
[2024-01-27T22:07:29.018Z] --> Using cache 33f7858b2c9c2c0a4098823656ce299a1ffc3e98236623eb6546eb73bd2350a8
[2024-01-27T22:07:29.019Z]
[2024-01-27T22:07:29.019Z] --> 33f7858b2c9c
[2024-01-27T22:07:29.021Z]
[2024-01-27T22:07:29.068Z] [2/2] STEP 1/12: FROM mcr.microsoft.com/devcontainers/universal:2-linux AS dev_containers_target_stage
[2024-01-27T22:07:29.177Z] [2/2] STEP 2/12: USER root
[2024-01-27T22:07:29.179Z]
[2024-01-27T22:07:29.194Z] --> Using cache 3939e9e2b13c3a870e3d13d838a0dd9bd2437433c8f5430c936e73c186889c36
--> 3939e9e2b13c
[2024-01-27T22:07:29.225Z] [2/2] STEP 3/12: RUN mkdir -p /tmp/dev-container-features
[2024-01-27T22:07:29.226Z]
[2024-01-27T22:07:29.249Z] --> Using cache 72b295c67b7ff05060581ad90f2e1bae1014276539282b8fc8dd85a2bb233fc0
--> 72b295c67b7f
[2024-01-27T22:07:29.290Z] [2/2] STEP 4/12: COPY --from=dev_containers_feature_content_normalize /tmp/build-features/ /tmp/dev-container-features
[2024-01-27T22:07:29.781Z] --> Using cache eeeed1eba6723b571cec896e014bec32e45394c3050bbc68dba084b9dd43cbed
--> eeeed1eba672
[2024-01-27T22:07:29.820Z] [2/2] STEP 5/12: RUN echo "_CONTAINER_USER_HOME=$( (command -v getent >/dev/null 2>&1 && getent passwd 'codespace' || grep -E '^codespace|^[^:]*:[^:]*:codespace:' /etc/passwd || true) | cut -d: -f6)" >> /tmp/dev-container-features/devcontainer-features.builtin.env && echo "_REMOTE_USER_HOME=$( (command -v getent >/dev/null 2>&1 && getent passwd 'codespace' || grep -E '^codespace|^[^:]*:[^:]*:codespace:' /etc/passwd || true) | cut -d: -f6)" >> /tmp/dev-container-features/devcontainer-features.builtin.env
[2024-01-27T22:07:29.843Z] --> Using cache 093fe9ac305c854b0109329647ba7bad35993627b58a65c3013ca0a7a0fbe95a
[2024-01-27T22:07:29.848Z]
--> 093fe9ac305c
[2024-01-27T22:07:29.890Z] [2/2] STEP 6/12: ENV SDKMAN_DIR="/usr/local/sdkman"
[2024-01-27T22:07:29.890Z]
[2024-01-27T22:07:29.925Z] --> Using cache 64151dd233df96dba0ec295fe2b340a5076d4915db1223ef056344669d9c110a
--> 64151dd233df
[2024-01-27T22:07:30.085Z] [2/2] STEP 7/12: ENV JAVA_HOME="/usr/local/sdkman/candidates/java/current"
[2024-01-27T22:07:30.147Z] --> Using cache f23ba5cfa5c6f1653732d960ac6be7251e28d4b2269964aacf75b3f055d9c1a3
--> f23ba5cfa5c6
[2024-01-27T22:07:30.233Z] [2/2] STEP 8/12: ENV PATH="/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:${PATH}"
[2024-01-27T22:07:30.239Z]
[2024-01-27T22:07:30.305Z] --> Using cache b97a47f7bd4462de6f54f645f64126c3d497c19c887540e5fe1639e931777d14
[2024-01-27T22:07:30.307Z]
--> b97a47f7bd44
[2024-01-27T22:07:30.308Z]
 [2024-01-27T22:07:30.408Z] [2/2] STEP 9/12: RUN --mount=type=bind,from=dev_containers_feature_content_source,source=java_0,target=/tmp/build-features-src/java_0     cp -ar /tmp/build-features-src/java_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/java_0  && cd /tmp/dev-container-features/java_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/java_0
[2024-01-27T22:07:31.830Z] cp: cannot access '/tmp/build-features-src/java_0': Permission denied
[2024-01-27T22:07:31.830Z]
[2024-01-27T22:07:32.268Z] Error: building at STEP "RUN --mount=type=bind,from=dev_containers_feature_content_source,source=java_0,target=/tmp/build-features-src/java_0 cp -ar /tmp/build-features-src/java_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/java_0  && cd /tmp/dev-container-features/java_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/java_0": while running runtime: exit status 1
[2024-01-27T22:07:32.288Z] Stop (4549 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-vorburger/container-features/0.54.1-1706393246427 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/universal:2-linux --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-enola-577cbb2e9b094215f15980dd5f49c2e1bb2879f51a769be6f23be75ff412ddd4-features -f /tmp/devcontainercli-vorburger/container-features/0.54.1-1706393246427/Dockerfile.extended /home/vorburger/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2024-01-27T22:07:32.297Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-vorburger/container-features/0.54.1-1706393246427 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/universal:2-linux --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-enola-577cbb2e9b094215f15980dd5f49c2e1bb2879f51a769be6f23be75ff412ddd4-features -f /tmp/devcontainercli-vorburger/container-features/0.54.1-1706393246427/Dockerfile.extended /home/vorburger/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2024-01-27T22:07:32.297Z]     at J$ (/home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:1253)
[2024-01-27T22:07:32.297Z]     at $J (/home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:997)
[2024-01-27T22:07:32.298Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-01-27T22:07:32.298Z]     at async tAA (/home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2024-01-27T22:07:32.299Z]     at async CC (/home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2024-01-27T22:07:32.299Z]     at async NeA (/home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:11107)
[2024-01-27T22:07:32.299Z]     at async MeA (/home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:10848)
[2024-01-27T22:07:32.335Z] Stop (8548 ms): Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/vorburger/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-8061b729-cfe5-4fee-9e2a-d7af1ab72fea1706393238847 --workspace-folder /home/vorburger/git/github.com/enola-dev/enola --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --id-label devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-01-27T22:07:32.335Z] Exit code 1
[2024-01-27T22:07:32.354Z] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/vorburger/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/vorburger/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-8061b729-cfe5-4fee-9e2a-d7af1ab72fea1706393238847 --workspace-folder /home/vorburger/git/github.com/enola-dev/enola --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/vorburger/git/github.com/enola-dev/enola --id-label devcontainer.config_file=/home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vorburger/git/github.com/enola-dev/enola/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-01-27T22:07:32.354Z] Exit code 1
``` 

I suspect that this is a much more of a generic "Podman dockerx emulation" bug than anything wrong in this repository itself.

It may well be related to that ancient (very annoying!) `:Z` SELinux "mismatch"?

Perhaps I'll further debug this some time - but not now! ("Filing" this, at least.)

**Comment by vorburger** [comment]
I got back to this today due to #1038, and noticed that it now works for me: 

```
Running the onCreateCommand from devcontainer.json...

[113397 ms] Start: Run in container:
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Cloning into '/home/codespace/.asdf'...
remote: Enumerating objects: 10385, done.
remote: Counting objects: 100% (258/258), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 10385 (delta 170), reused 197 (delta 142), pack-reused 10127 (from 2)
Receiving objects: 100% (10385/10385), 3.90 MiB | 28.91 MiB/s, done.
Resolving deltas: 100% (6119/6119), done.
Note: switching to 'ccdd47df9b73d0a22235eb06ad4c48eb57360832'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

OS:
Linux 11405d12f9d7 6.12.11-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jan 24 04:59:58 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

BASH VERSION:
5.0.17(1)-release

ASDF VERSION:
v0.14.0-ccdd47d

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/home/codespace/.asdf
ASDF_DIR=/home/codespace/.asdf
ASDF_CONFIG_FILE=/home/codespace/.asdfrc

No plugins installed
ASDF INSTALLED PLUGINS:


initializing plugin repository...Cloning into '/home/codespace/.asdf/repository'...
remote: Enumerating objects: 6174, done.
remote: Counting objects: 100% (1825/1825), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 6174 (delta 1807), reused 1770 (delta 1770), pack-reused 4349 (from 2)
Receiving objects: 100% (6174/6174), 1.46 MiB | 17.75 MiB/s, done.
Resolving deltas: 100% (3394/3394), done.
Downloading Bun v1.1.45...
Archive:  /tmp/asdf-bun.x5Ub/bun.zip
  inflating: /home/codespace/.asdf/downloads/bun/1.1.45/bun  
Installing Bun v1.1.45...
Bun v1.1.45 is installed successfully!
Downloading https://github.com/protocolbuffers/protobuf/releases/download/v29.2/protoc-29.2-linux-x86_64.zip
asdf: Warn: You have configured asdf to preserve downloaded files (with always_keep_download=yes or --keep-download). But
asdf: Warn: the current plugin (protoc) does not support that. Downloaded files will not be preserved.
bun             1.1.45          /workspaces/enola/.tool-versions
protoc          29.2            /workspaces/enola/.tool-versions
libprotoc 29.2
##O=-#    #                                                                                                                                                #=#=-  #     #                                                                                                                                                                                                                                                                                                        ######                                                                                                                                                     ################                                                                                                                                           #########################                                                                                                                                  ###################################                                                                                                                        ############################################                                                                                                               ######################################################                                                                                                     ###############################################################                                                                                            #########################################################################                                                                                  ##################################################################################                                                                         ############################################################################################                                                               #####################################################################################################                                                      ###############################################################################################################                                            ########################################################################################################################                                   ##################################################################################################################################                         #####################################################################################################################################                      ###############################################################################################################################################            ########################################################################################################################################################   ##################################################################################################################################################################################################################################################################################################################################### 100.0%
OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz
OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz: OK
asdf: Warn: You have configured asdf to preserve downloaded files (with always_keep_download=yes or --keep-download). But
asdf: Warn: the current plugin (java) does not support that. Downloaded files will not be preserved.
openjdk 21.0.2 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)
++ go env GOPATH
+ GO_BIN_PATH=/go/bin
+ BZL=/go/bin/bazelisk
+ go install github.com/bazelbuild/bazelisk@v1.19.0
go: downloading github.com/bazelbuild/bazelisk v1.19.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/hashicorp/go-version v1.6.0
go: downloading github.com/bgentry/go-netrc v0.0.0-20140422174119-9fd32a8b3d3d
go: downloading golang.org/x/term v0.13.0
go: downloading golang.org/x/sys v0.13.0
+ go install github.com/bazelbuild/buildtools/buildifier@latest
go: downloading github.com/bazelbuild/buildtools v0.0.0-20250204160707-ad48c76ab9b5
go: downloading github.com/golang/protobuf v1.5.0
go: downloading google.golang.org/protobuf v1.33.0
+ go install github.com/bazelbuild/buildtools/buildozer@latest
+ ln -fs /go/bin/bazelisk /go/bin/bazel
+ ln -fs /go/bin/bazelisk /go/bin/b
+ set +u
+ '[' -n '' ']'
+ set -u
+ /go/bin/bazelisk version
2025/02/05 19:16:57 Downloading https://releases.bazel.build/8.0.0/release/bazel-8.0.0-linux-x86_64...
Downloading: 61 MB out of 61 MB (100%) 
Bazelisk version: development
Extracting Bazel installation...
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Starting local Bazel server and connecting to it...
Build label: 8.0.0
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Mon Dec 09 18:00:43 2024 (1733767243)
Build timestamp: 1733767243
Build timestamp as int: 1733767243
Running the postCreateCommand from Feature 'ghcr.io/devcontainers/features/git-lfs:1'...

[160791 ms] Start: Run in container:
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Fetching git lfs artifacts...
(!) Skipping automatic 'git lfs pull' because no git lfs files were detected
```

This is meanwhile on Fedora 41 with Podman 5.3.2. But the fix may well have been made in the VSC extension.

Ergo, closing as FIXED (respectively OBSOLETE).
