### ISSUE TITLE
rules_go could not detect host go version when running Bazel Build under ASDF

### ISSUE THREAD

**Issue by vorburger** [enola-dev/enola#532]
With the current `main` (as of `bcf744b`) IFF running `./test.bash` in an environment of `tools/asdf/install.bash` (ASDF), then:

```
Loading: 0 packages loaded
INFO: Repository rules_go~0.44.2~go_sdk~main___host_0 instantiated at:
  <builtin>: in <toplevel>
Repository rule go_host_sdk_rule defined at:
  /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_go~0.44.2/go/private/sdk.bzl:29:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_go~0.44.2~go_sdk~main___host_0':
   Traceback (most recent call last):
        File "/home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_go~0.44.2/go/private/sdk.bzl", line 23, column 30, in _go_host_sdk_impl
                goroot = _detect_host_sdk(ctx)
        File "/home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_go~0.44.2/go/private/sdk.bzl", line 538, column 13, in _detect_host_sdk
                fail("Could not detect host go version")
Error in fail: Could not detect host go version
ERROR: <builtin>: fetching go_host_sdk_rule rule //:rules_go~0.44.2~go_sdk~main___host_0: Traceback (most recent call last):
        File "/home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_go~0.44.2/go/private/sdk.bzl", line 23, column 30, in _go_host_sdk_impl
                goroot = _detect_host_sdk(ctx)
        File "/home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_go~0.44.2/go/private/sdk.bzl", line 538, column 13, in _detect_host_sdk
                fail("Could not detect host go version")
Error in fail: Could not detect host go version
ERROR: /home/vorburger/git/github.com/enola-dev/enola/cli/BUILD:43:11: While resolving toolchains for target //cli:src/test/java/dev/enola/cli/ClasspathHellDuplicatesCheckerTest (310ec0d): invalid registered toolchain '@go_toolchains//:all': while parsing '@go_toolchains//:all': no such package '@@rules_go~0.44.2~go_sdk~main___host_0//': Could not detect host go version
ERROR: Analysis of target '//cli:src/test/java/dev/enola/cli/ClasspathHellDuplicatesCheckerTest' failed; build aborted
INFO: Elapsed time: 0.648s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: No test targets were found, yet testing was requested
```

**Comment by vorburger** [comment]
Glancing at [this](https://github.com/bazelbuild/rules_go/blob/8c014fd0798b1c2965d4dc97e11089bc1d43490a/go/private/sdk.bzl#L532), I figured and tested that this does the trick:

```bash
$ GOROOT=~/.asdf/installs/golang/1.21.7/ ./test.bash
```

or without hard-coding:

```bash
GOROOT=$(asdf where golang)/go/ ./test.bash
```

I'll try to add that to the script.

**Comment by vorburger** [comment]
No, this ^^^ is a stupid fix for this problem - because it's needed in every script that uses Bazel...

... and the VSC Bazel Java integration is still broken - due to the same error! 😭 

The root cause of this is that `rules_bazel` in v0.44.2 doesn't seem to work with the ASDF `go` _"shim",_ where `which go` is a Bash script which runs another bash script which finds the real native `go`.

Interestingly, with #444 which bumps `rules_bazel` in v0.44.2 this problem disappears... at least locally (but on CI it still fails, TBD).

Alternatively, it may be easier to simply not install `go` with ASDF after all?!
