### ISSUE TITLE
Could not create symlink from /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/remotejdk21_linux/WORKSPACE to /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/local_jdk/WORKSPACE

### ISSUE THREAD

**Issue by vorburger** [enola-dev/enola#574]
This problem just start appearing, must probably due to and since #558:

```bash
$ ./enola help
Computing main repo mapping:
Loading:
Loading: 0 packages loaded
Analyzing: target //cli:enola_deploy.jar (1 packages loaded, 0 targets configured)
Analyzing: target //cli:enola_deploy.jar (1 packages loaded, 0 targets configured)
[0 / 1] checking cached actions
INFO: Repository local_jdk instantiated at:
  /home/vorburger/git/github.com/enola-dev/enola/WORKSPACE.bazel:84:25: in <toplevel>
  /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_jvm_external~6.0/setup.bzl:12:32: in rules_jvm_external_setup
  /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_java~7.4.0/java/repositories.bzl:525:19: in rules_java_dependencies
  /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_java~7.4.0/java/repositories.bzl:69:10: in local_jdk_repo
  /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/bazel_tools/tools/build_defs/repo/utils.bzl:240:18: in maybe
  /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_java~7.4.0/toolchains/local_java_repository.bzl:315:32: in local_java_repository
Repository rule _local_java_repository_rule defined at:
  /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_java~7.4.0/toolchains/local_java_repository.bzl:270:46: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_jdk':
   Traceback (most recent call last):
        File "/home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_java~7.4.0/toolchains/local_java_repository.bzl", line 240, column 31, in _local_java_repository_impl
                repository_ctx.symlink(file, file.basename)
Error in symlink: java.io.IOException: Could not create symlink from /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/remotejdk21_linux/WORKSPACE to /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/local_jdk/WORKSPACE: /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/local_jdk/WORKSPACE (File exists)
ERROR: /home/vorburger/git/github.com/enola-dev/enola/WORKSPACE.bazel:84:25: fetching _local_java_repository_rule rule //external:local_jdk: Traceback (most recent call last):
        File "/home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_java~7.4.0/toolchains/local_java_repository.bzl", line 240, column 31, in _local_java_repository_impl
                repository_ctx.symlink(file, file.basename)
Error in symlink: java.io.IOException: Could not create symlink from /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/remotejdk21_linux/WORKSPACE to /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/local_jdk/WORKSPACE: /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/local_jdk/WORKSPACE (File exists)
ERROR: Analysis of target '//cli:enola_deploy.jar' failed; build aborted: java.io.IOException: Could not create symlink from /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/remotejdk21_linux/WORKSPACE to /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/local_jdk/WORKSPACE: /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/local_jdk/WORKSPACE (File exists)
INFO: Elapsed time: 0.427s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
FAILED:
```

**Comment by vorburger** [comment]
Huh, even a `bazelisk clean && sudo rm -rf ~/.cache/bazel/` does not seem to fix this?!

But it only happens for `./enola`, whereas `bazelisk build //cli:enola_deploy.jar`, and e.g. `bazelisk run //cli:enola -- --version` still works just fine.

I wonder if this is a hint:

```
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: Running Bazel server needs to be killed, because the startup options are different.
```

I think I'

**Comment by vorburger** [comment]
This has something to do with with adding the Bazel JDK to the `PATH` and/or setting `JAVA_HOME` to it.

For now, I'll try to do #553 without that (and just use `"$bazel_java_home"/bin/java` in `./enola`).
